version: "3.9"

services:

  redis-server:
    image: redis:6.2-alpine
    restart: always
    volumes:
      - ./redis-server:/data/redis
      - ./redis.conf:/usr/local/etc/redis/redis.conf
    ports:
      - '6379:6379'
    command: [ "redis-server", "/usr/local/etc/redis/redis.conf" ]

  db:
    image: mysql:5.7.38-oracle
    container_name: docker_blogs
    environment:
      - MYSQL_TCP_PORT=3307
      - MYSQL_DATABASE=blogs
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_PASSWORD=root
      - MYSQL_NAME=root
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 1024M
    ports:
      - 3307:3307
    command: ['mysqld', '--character-set-server=utf8', '--collation-server=utf8_unicode_ci']
  web:
    build: .
    volumes:
      - .:/code
    ports:
      - 8001:8001
    environment:
      - DATABASE_NAME=blogs
      - DATABASE_USER=root
      - DATABASE_PASSWORD=root
      - DATABASE_HOST=db
      - DATABASE_PORT=3307
    depends_on:
      - db
    command: python manage.py runserver 0.0.0.0:8001
networks:
  default:
    external:
      name: blogs