version: "3.9"

services:

  redis-server:
    image: "redis:${REDIS_VERSION}"
    restart: always
    volumes:
      - ./redis-server:/data/redis
      - ./redis.conf:/usr/local/etc/redis/redis.conf
    ports:
      - '6379:6379'
    command: [ "redis-server", "/usr/local/etc/redis/redis.conf" ]

  db:
    env_file:
      - ./.env
    image: "mysql:${MYSQL_VERSION}"
    container_name: docker_blogs
    environment:
      - MYSQL_TCP_PORT=${MYSQL_TCP_PORT}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_NAME=${MYSQL_NAME}
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 1024M
    ports:
      - 3307:3307
    command: ['mysqld', '--character-set-server=utf8', '--collation-server=utf8_unicode_ci']

  web:
    build: .
    volumes:
      - .:/code
    ports:
      - 8001:8001
    env_file:
      - ./.env
    environment:
      - DJANGO_SETTINGS_MODULE=${DJANGO_SETTINGS_MODULE}
    depends_on:
      - db
      - redis-server
    command:  python manage.py runserver 0.0.0.0:8001

  celery:
    build:
       context: .
    container_name: celery
    command: celery -A celery worker --loglevel=info
    volumes:
       - .:/code
    env_file:
      - ./.env
    depends_on:
      - db
      - redis-server

networks:
  default:
    external:
      name: blogs